#!/usr/bin/env bash
# ============================================================================
# One-time setup: PKI, broker credentials, Java truststore, rendered configs.
#
# In production this is what your secret manager / cert-manager / Vault does.
# Here it is a script so the demo is self-contained and reproducible.
#
#   ./scripts/bootstrap.sh          # generate if missing
#   ./scripts/bootstrap.sh --force  # wipe and regenerate everything
# ============================================================================
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CERTS="$ROOT/certs"
SECRETS="$ROOT/secrets"
MOSQ_IMAGE="eclipse-mosquitto:2.0.22"
DAYS=825

log() { printf '\033[36m==>\033[0m %s\n' "$*"; }

if [[ "${1:-}" == "--force" ]]; then
  log "Wiping existing certs and secrets"
  rm -rf "$CERTS" "$SECRETS"
  rm -f "$ROOT"/broker/edge-site*/config/mosquitto.conf
fi
mkdir -p "$CERTS" "$SECRETS"

# ---------------------------------------------------------------------------
# 1. Certificate authority
# ---------------------------------------------------------------------------
if [[ ! -f "$CERTS/ca.crt" ]]; then
  log "Creating private CA"
  openssl req -x509 -newkey rsa:4096 -sha256 -days 3650 -nodes \
    -keyout "$CERTS/ca.key" -out "$CERTS/ca.crt" \
    -subj "/C=IN/O=Demo IoT/OU=Platform/CN=Demo IoT Root CA" \
    -addext "basicConstraints=critical,CA:TRUE,pathlen:0" \
    -addext "keyUsage=critical,keyCertSign,cRLSign" 2>/dev/null
else
  log "CA already present, reusing"
fi

# ---------------------------------------------------------------------------
# 2. Server certificates
#    SANs must cover both the compose service name (how containers dial it) and
#    localhost (how you dial it from your laptop with mosquitto_sub).
# ---------------------------------------------------------------------------
issue_server_cert() {
  local name="$1" sans="$2"
  [[ -f "$CERTS/$name.crt" ]] && { log "cert $name already present"; return; }
  log "Issuing server cert: $name  [$sans]"
  openssl req -newkey rsa:2048 -sha256 -nodes \
    -keyout "$CERTS/$name.key" -out "$CERTS/$name.csr" \
    -subj "/C=IN/O=Demo IoT/OU=Brokers/CN=$name" 2>/dev/null
  openssl x509 -req -in "$CERTS/$name.csr" -sha256 -days "$DAYS" \
    -CA "$CERTS/ca.crt" -CAkey "$CERTS/ca.key" -CAcreateserial \
    -out "$CERTS/$name.crt" \
    -extfile <(printf 'subjectAltName=%s\nextendedKeyUsage=serverAuth\nkeyUsage=critical,digitalSignature,keyEncipherment\n' "$sans") \
    2>/dev/null
  rm -f "$CERTS/$name.csr"
}

issue_server_cert cloud-broker       "DNS:cloud-broker,DNS:localhost,IP:127.0.0.1"
issue_server_cert edge-broker-site1  "DNS:edge-broker-site1,DNS:localhost,IP:127.0.0.1"
issue_server_cert edge-broker-site2  "DNS:edge-broker-site2,DNS:localhost,IP:127.0.0.1"

# ---------------------------------------------------------------------------
# 3. Java truststore (the Spring services verify the broker chain against this)
# ---------------------------------------------------------------------------
# Deliberately the JDK's well-known default, and deliberately not randomised.
# A truststore holds only public certificates -- here, one CA cert and no private
# key -- so this password protects integrity, not confidentiality. Randomising it
# would imply a secret that does not exist. Every genuinely secret value below IS
# random per install and never leaves this machine.
TRUSTSTORE_PASS="changeit"
if [[ ! -f "$CERTS/truststore.p12" ]]; then
  log "Building PKCS12 truststore for the Spring services"
  keytool -importcert -noprompt -trustcacerts \
    -alias demo-iot-ca -file "$CERTS/ca.crt" \
    -keystore "$CERTS/truststore.p12" -storetype PKCS12 \
    -storepass "$TRUSTSTORE_PASS" >/dev/null
fi

# ---------------------------------------------------------------------------
# 4. Broker credentials
#    Passwords are random per install and never committed. mosquitto_passwd
#    runs inside the official image so no host dependency is needed.
# ---------------------------------------------------------------------------
rand_pw() { openssl rand -base64 24 | tr -d '/+=' | cut -c1-24; }

if [[ ! -f "$SECRETS/credentials.env" ]]; then
  log "Generating broker credentials"
  {
    echo "# Generated by scripts/bootstrap.sh -- DO NOT COMMIT"
    echo "CLOUD_APP_PASSWORD=$(rand_pw)"
    echo "EDGE_APP_PASSWORD=$(rand_pw)"
    echo "BRIDGE_SITE1_PASSWORD=$(rand_pw)"
    echo "BRIDGE_SITE2_PASSWORD=$(rand_pw)"
    echo "OBSERVER_PASSWORD=$(rand_pw)"
    echo "TRUSTSTORE_PASSWORD=$TRUSTSTORE_PASS"
  } > "$SECRETS/credentials.env"
  chmod 600 "$SECRETS/credentials.env"
else
  log "Credentials already present, reusing"
fi
# shellcheck disable=SC1090
set -a; source "$SECRETS/credentials.env"; set +a

# docker compose interpolates ${VAR} in the compose file from .env in the
# project directory, so mirror the generated credentials there. Both files are
# gitignored; nothing in this repo ever contains a real password.
cp "$SECRETS/credentials.env" "$ROOT/.env"
chmod 600 "$ROOT/.env"

mk_passwd_file() {
  # mk_passwd_file <output-path> <user:pass> [<user:pass> ...]
  local out="$1"; shift
  local dir base first
  dir="$(dirname "$out")"; base="$(basename "$out")"; first=1
  rm -f "$out"
  for pair in "$@"; do
    local flag="-b"
    [[ $first -eq 1 ]] && flag="-c -b" && first=0
    # shellcheck disable=SC2086
    docker run --rm -v "$dir:/work" -w /work "$MOSQ_IMAGE" \
      mosquitto_passwd $flag "$base" "${pair%%:*}" "${pair#*:}"
  done
  # Docker Desktop bind mounts preserve host uid/gid, and mosquitto drops to
  # uid 1883 inside the container -- so these have to stay world-readable here.
  # In production these files are delivered by the secret store, owned by the
  # broker user, mode 0600.
  chmod 644 "$out"
}

log "Writing broker password files"
mk_passwd_file "$ROOT/broker/cloud/config/passwd" \
  "cloud-app:$CLOUD_APP_PASSWORD" \
  "bridge-site1:$BRIDGE_SITE1_PASSWORD" \
  "bridge-site2:$BRIDGE_SITE2_PASSWORD" \
  "observer:$OBSERVER_PASSWORD"

mk_passwd_file "$ROOT/broker/edge-site1/config/passwd" \
  "edge-app:$EDGE_APP_PASSWORD" "observer:$OBSERVER_PASSWORD"
mk_passwd_file "$ROOT/broker/edge-site2/config/passwd" \
  "edge-app:$EDGE_APP_PASSWORD" "observer:$OBSERVER_PASSWORD"

# ---------------------------------------------------------------------------
# 5. Render bridge configs
#    mosquitto.conf has no variable interpolation, so the bridge password is
#    injected here at "deploy" time from the template.
# ---------------------------------------------------------------------------
render_bridge() {
  local site="$1" pw="$2"
  local tpl="$ROOT/broker/edge-$site/config/mosquitto.conf.tpl"
  local out="$ROOT/broker/edge-$site/config/mosquitto.conf"
  log "Rendering bridge config for $site"
  sed "s|__BRIDGE_PASSWORD__|$pw|" "$tpl" > "$out"
  chmod 644 "$out"
}
render_bridge site1 "$BRIDGE_SITE1_PASSWORD"
render_bridge site2 "$BRIDGE_SITE2_PASSWORD"


# ---------------------------------------------------------------------------
# 6. Preseed the MQTT Explorer UI with all three brokers
#    INITIAL_CONFIG is written by the container on first start if it has no
#    settings yet, so the UI opens with cloud / site 1 / site 2 already listed
#    and nobody has to retype a password to look at a topic tree.
#
#    Subscriptions are QoS 0 on purpose: an inspection tool must never cause the
#    broker to queue messages on its behalf. It is there to watch the system,
#    not to become part of it.
# ---------------------------------------------------------------------------
render_ui_config() {
  python3 - "$OBSERVER_PASSWORD" <<'PYEOF'
import json, sys
pw = sys.argv[1]

def connection(cid, name, host):
    return {
        "configVersion": 1,
        "id": cid,
        "name": name,
        "type": "mqtt",
        "protocol": "mqtt",
        "host": host,
        "port": 1883,
        "encryption": False,
        "certValidation": True,
        "clientId": "mqtt-explorer-" + cid,
        "username": "observer",
        "password": pw,
        # "$$SYS" not "$SYS": this string is written into .env, and docker
        # compose expands $VAR when it substitutes the value into the compose
        # file. "$$" is compose's escape for a literal "$".
        "subscriptions": [{"topic": "#", "qos": 0}, {"topic": "$$SYS/#", "qos": 0}],
    }

config = {
    "ConnectionManager_connections": {
        "cloud": connection("cloud", "Cloud broker (all sites)", "cloud-broker"),
        "site1": connection("site1", "Site 1 broker (on-site)", "edge-broker-site1"),
        "site2": connection("site2", "Site 2 broker (on-site)", "edge-broker-site2"),
    }
}
print(json.dumps(config, separators=(",", ":")))
PYEOF
}

UI_CONFIG="$(render_ui_config)"
# Replace any previous line, then append the current one.
grep -v '^MQTT_UI_INITIAL_CONFIG=' "$ROOT/.env" > "$ROOT/.env.tmp" || true
mv "$ROOT/.env.tmp" "$ROOT/.env"
printf 'MQTT_UI_INITIAL_CONFIG=%s\n' "$UI_CONFIG" >> "$ROOT/.env"
chmod 600 "$ROOT/.env"
log "MQTT Explorer preseeded with cloud, site1 and site2"

# ---------------------------------------------------------------------------
# 7. Permissions mosquitto expects (it drops to uid 1883 inside the container)
# ---------------------------------------------------------------------------
chmod 644 "$CERTS"/*.crt "$CERTS"/truststore.p12
chmod 644 "$CERTS"/*.key

cat <<EOF

  Bootstrap complete.

    CA + server certs   $CERTS
    Credentials         $SECRETS/credentials.env  (mirrored to .env)
    Bridge configs      broker/edge-site{1,2}/config/mosquitto.conf

  Next:  docker compose up -d --build

EOF
